### ISSUE TITLE
Wrong MCC folder

### ISSUE THREAD

**Issue by Chinchila01** [executionByFork/MCC_Mod_Manager#8]
Hey,

Is this supposed to work only with Halo Reach?
I bought only the first Halo and this tool doesn't working.

Checking the code, I see you check for @"\haloreach\haloreach.dll" in the chkHomeDir function. This file isn't present because I don't have Halo Reach.

Shouldn't it check for any of the available games?

**Comment by executionByFork** [comment]
Thank you for bringing that to my attention, that's an oversight on my part. This tool should work with any halo in MCC. That check is just to make sure the user is selecting the correct install folder. I'll put out a patch for it, but for now if you go into `MCC_Mod_manager.cfg` you should be able to manually change the path to something like `"C:\\Program Files (x86)\\Steam\\steamapps\\common\\Halo The Master Chief Collection"` (or where ever the install location is)

**Comment by executionByFork** [comment]
I'll try to push out beta0.8 to releases soon. That version will fix the issue. During development of beta0.8 with Darksound I ran into a couple of issues and ended up getting busy with other things, so development for this was put on hold for a while. I'm going to try and get back to polishing up this tool so it can be brought out of beta

**Comment by executionByFork** [comment]
Beta0.8 has been released with the fix in [cce911c ](https://github.com/executionByFork/MCC_Mod_Manager/commit/cce911c74a839e7b2d1f873dd218c49d28a5e3f2)
